#!/bin/bash

. /etc/init.d/functions

stop() {
    # code to stop app comes here 
    # example: killproc program_name
    killproc factory-monitord
}

start() {
    # code to start app comes here 
    # example: daemon program_name &
    daemon /usr/sbin/factory-monitord &
}


case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       status factory-monitord
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
