#!/bin/bash

# switch UID (su <naveen>)
su factmon
while [ 1 ]
do
# call daemon script 
date >> /var/lib/factory-monitor/monitor_output.txt
python /var/lib/factory-monitor/monitor.py >> /var/lib/factory-monitor/monitor_output.txt
sleep 15m
done

exit 0 
